# Generated by Django 3.2.10 on 2022-05-08 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinMnemonics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_phrase', models.TextField()),
                ('xpub', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'bitcoin mnemonics',
                'verbose_name_plural': 'bitcoin mnemonics',
                'db_table': 'bitcoin_mnemonics',
            },
        ),
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_symbol', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('available_balance', models.CharField(max_length=300)),
                ('account_balance', models.CharField(max_length=300)),
                ('frozen', models.BooleanField(default=False)),
                ('customer_id', models.CharField(max_length=300)),
                ('currency', models.CharField(default='USD', max_length=300)),
                ('ledger_id', models.CharField(max_length=300)),
                ('xpub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.bitcoinmnemonics')),
            ],
            options={
                'verbose_name': 'ledger account',
                'verbose_name_plural': 'ledger accounts',
                'db_table': 'ledger_account',
            },
        ),
    ]
