# Generated by Django 3.2.10 on 2022-05-09 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('derivation_key', models.IntegerField()),
                ('address_key', models.CharField(max_length=300)),
                ('coin_symbol', models.CharField(max_length=300)),
                ('xpub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.bitcoinmnemonics')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'address',
                'db_table': 'address',
            },
        ),
    ]
