# Generated by Django 3.2.10 on 2022-05-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedCoinMnemonics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_phrase', models.TextField()),
                ('xpub', models.CharField(blank=True, max_length=500, null=True)),
                ('coin', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'added_coin mnemonics',
                'verbose_name_plural': 'added_coin mnemonics',
                'db_table': 'added_coin_mnemonics',
            },
        ),
    ]
